EssayGrading_G4/EssayGrading_G4/src/java/entity/User.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

public class User {
    private int UserID; 
    private String Username;
    private String Email;
    private String Password;
    private int IsActive;
    private int RoleID;

    public User() {
    }

    public User(int UserID, String Username, String Email, String Password, int IsActive, int RoleID) {
        this.UserID = UserID;
        this.Username = Username;
        this.Email = Email;
        this.Password = Password;
        this.IsActive = IsActive;
        this.RoleID = RoleID;
    }

    public int getUserID() {
        return UserID;
    }

    public void setUserID(int UserID) {
        this.UserID = UserID;
    }

    public String getUsername() {
        return Username;
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public int getIsActive() {
        return IsActive;
    }

    public void setIsActive(int IsActive) {
        this.IsActive = IsActive;
    }

    public int getRoleID() {
        return RoleID;
    }

    public void setRoleID(int RoleID) {
        this.RoleID = RoleID;
    }

    

    
    
}

EssayGrading_G4/EssayGrading_G4/web/teacher/about_student.jsp
<%-- 
    Document   : about_student
    Created on : Mar 12, 2024, 11:38:46 AM
    Author     : -Pc-
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %> 
<%@ page import="java.net.URLEncoder" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>About Student</title>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css"
              href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        
        
        <style type="text/css">
            body{
                color: #6F8BA4;
                margin-top:20px;
            }
            .section {
                padding: 100px 0;
                position: relative;
            }
            .gray-bg {
                background-color: #f5f5f5;
            }
            img {
                max-width: 100%;
            }
            img {
                vertical-align: middle;
                border-style: none;
            }
            /* About Me 
            ---------------------*/
            .about-text h3 {
                font-size: 45px;
                font-weight: 700;
                margin: 0 0 6px;
            }
            @media (max-width: 767px) {
                .about-text h3 {
                    font-size: 35px;
                }
            }
            .about-text h6 {
                font-weight: 600;
                margin-bottom: 15px;
            }
            @media (max-width: 767px) {
                .about-text h6 {
                    font-size: 18px;
                }
            }
            .about-text p {
                font-size: 18px;
                max-width: 450px;
            }
            .about-text p mark {
                font-weight: 600;
                color: #20247b;
            }

            .about-list {
                padding-top: 10px;
            }
            .about-list .media {
                padding: 5px 0;
            }
            .about-list label {
                color: #20247b;
                font-weight: 600;
                width: 88px;
                margin: 0;
                position: relative;
            }
            .about-list label:after {
                content: "";
                position: absolute;
                top: 0;
                bottom: 0;
                right: 11px;
                width: 1px;
                height: 12px;
                background: #20247b;
                -moz-transform: rotate(15deg);
                -o-transform: rotate(15deg);
                -ms-transform: rotate(15deg);
                -webkit-transform: rotate(15deg);
                transform: rotate(15deg);
                margin: auto;
                opacity: 0.5;
            }
            .about-list p {
                margin: 0;
                font-size: 15px;
            }

            @media (max-width: 991px) {
                .about-avatar {
                    margin-top: 30px;
                }
            }

            .about-section .counter {
                padding: 22px 20px;
                background: #ffffff;
                border-radius: 10px;
                box-shadow: 0 0 30px rgba(31, 45, 61, 0.125);
            }
            .about-section .counter .count-data {
                margin-top: 10px;
                margin-bottom: 10px;
            }
            .about-section .counter .count {
                font-weight: 700;
                color: #20247b;
                margin: 0 0 5px;
            }
            .about-section .counter p {
                font-weight: 600;
                margin: 0;
            }
            mark {
                background-image: linear-gradient(rgba(252, 83, 86, 0.6), rgba(252, 83, 86, 0.6));
                background-size: 100% 3px;
                background-repeat: no-repeat;
                background-position: 0 bottom;
                background-color: transparent;
                padding: 0;
                color: currentColor;
            }
            .theme-color {
                color: #fc5356;
            }
            .dark-color {
                color: #20247b;
            }

            .theme-color.lead{
                text-transform: uppercase;
            }
            /*female, male icon*/
            .male-icon {
                color: blue; /* Màu xanh */
            }

            .female-icon {
                color: #ff69b4; /* Màu hồng */
            }

            /* CSS cho nút "Back" */
            .back-button {
                position: fixed;
                top: 20px; /* Khoảng cách từ trên xuống */
                right: 20px; /* Khoảng cách từ phải sang */
                background-color: #007bff; /* Màu nền của nút */
                color: white; /* Màu chữ của nút */
                padding: 10px 20px; /* Kích thước của nút */
                border-radius: 5px; /* Bo tròn góc của nút */
                text-decoration: none; /* Loại bỏ gạch chân cho văn bản trong nút */
                font-weight: bold; /* Đậm chữ của nút */
                z-index: 9999; /* Layer cao nhất */
            }

        </style>
    </head>
    <body>
        <section class="section about-section gray-bg" id="about">

            <%
    // Lấy giá trị của biến course_name từ session
    String courseName = (String) session.getAttribute("course_name");
            %>

            <div class="container">
                <div class="row align-items-center flex-row-reverse">
                    <div class="col-lg-6">
                        <div class="about-text go-to">
                            <a href="managestudent?course_name=<%= URLEncoder.encode(courseName.trim(), "UTF-8") %>" class="back-button">
                                Back
                            </a>
                            <h3 class="dark-color">About ${student.fullname}
                                <c:choose>
                                    <c:when test="${student.gender eq 'male'}">
                                        <span class="male-icon">&#9794;</span>
                                    </c:when>
                                    <c:when test="${student.gender eq 'female'}">
                                        <span class="female-icon">&#9792;</span>
                                    </c:when>

                                </c:choose> 
                            </h3>
                            <h6 class="theme-color lead">${student.role.role_name}</h6>
                            <!--                            <p>I <mark>design and develop</mark> services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores. My passion is to design digital user experiences through the bold interface and meaningful interactions.</p>-->
                            <p>${student.description} </p>
                            <div class="row about-list">
                                <div class="col-md-6">
                                    <div class="media">
                                        <label>Fullname</label>
                                        <p>${student.fullname}</p>

                                    </div>

                                    <div class="media">
                                        <label>Residence</label>
                                        <p>${student.country}</p>
                                    </div>
                                    <div class="media">
                                        <label>Address</label>
                                        <p>${student.address}</p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="media">
                                        <label>E-mail</label>
                                        <p><a  class="__cf_email__" data-cfemail="650c0b030a25010a08040c0b4b060a08">${student.email}</a></p>
                                    </div>
                                    <div class="media">
                                        <label>Phone</label>
                                        <p>${student.phone}</p>
                                    </div>
                                    <div class="media">
                                        <label>Dob</label>
                                        <p>${student.dob}</p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-avatar">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" title alt>
                        </div>
                    </div>
                </div>
                <div class="counter">
                    <div class="row">
                        <c:forEach items="${listCourse}" var="c">
                            <div class="col-6 col-lg-3">
                                <div class="count-data text-center">
                                    <h6 class="count h2" data-to="500" data-speed="500">500</h6>
                                    <p class="m-0px font-w-600">${c.course_name}</p>
                                </div>
                            </div>
                        </c:forEach>
                        <!--                        <div class="col-6 col-lg-3">
                                                    <div class="count-data text-center">
                                                        <h6 class="count h2" data-to="500" data-speed="500">500</h6>
                                                        <p class="m-0px font-w-600">Happy Clients</p>
                                                    </div>
                                                </div>
                                                <div class="col-6 col-lg-3">
                                                    <div class="count-data text-center">
                                                        <h6 class="count h2" data-to="150" data-speed="150">150</h6>
                                                        <p class="m-0px font-w-600">Project Completed</p>
                                                    </div>
                                                </div>
                                                <div class="col-6 col-lg-3">
                                                    <div class="count-data text-center">
                                                        <h6 class="count h2" data-to="850" data-speed="850">850</h6>
                                                        <p class="m-0px font-w-600">Photo Capture</p>
                                                    </div>
                                                </div>
                                                <div class="col-6 col-lg-3">
                                                    <div class="count-data text-center">
                                                        <h6 class="count h2" data-to="190" data-speed="190">190</h6>
                                                        <p class="m-0px font-w-600">Telephonic Talk</p>
                                                    </div>
                                                </div>-->
                    </div>
                </div>
            </div>
        </section>
        <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript">

        </script>
    </body>
</html>

EssayGrading_G4/EssayGrading_G4/web/teacher/addAnswer.jsp
<%-- 
    Document   : addAnswer
    Created on : Mar 6, 2024, 12:19:46 PM
    Author     : -Pc-
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Thêm Câu Trả Lời Mới</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <!-- Font Awesome CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    </head>

    <body>
        <div class="container mt-5">
            <h2 class="text-center mb-4">Thêm Câu Trả Lời Mới</h2>

            <form action="/QuizPractice/addAnswer" method="get" id="addAnswerForm">
                <div class="form-group">
                    <label for="answerText">Nội dung câu trả lời:</label>
                    <textarea class="form-control" rows="3" id="answerText" name="answerText" required></textarea>
                </div>
                <div class="form-check">
                    
                    <input type="checkbox" class="form-check-input" id="isCorrect" name="isCorrect">
                    <label class="form-check-label" for="isCorrect">Câu trả lời đúng</label>
                </div>
                <button type="submit" class="btn btn-primary mt-3" >Thêm Câu Trả Lời</button>
            </form>
        </div>

        <!-- Bootstrap JS và Popper.js -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!--        <script>
                    function redirectToAnswerList() {
                        // Redirect to the desired URL when the button is clicked
                        window.location.href = '/QuizPractice/addAnswer'; // Thay thế bằng URL thực tế
                    }
        </script>-->
    </body>

</html>

EssayGrading_G4/EssayGrading_G4/web/teacher/addQuestion.jsp
<%-- 
    Document   : addQuestion
    Created on : Mar 6, 2024, 9:34:23 AM
    Author     : -Pc-
--%>

<%@ page contentType="text/html" pageEncoding="UTF-8"  %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Thêm Câu Hỏi</title>
        <!-- Add your CSS styles here -->
        <link rel="stylesheet" type="text/css" href="path/to/your/styles.css">
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Add your additional stylesheets or frameworks here -->
        <style>
            body {
                background-color: #f8f9fa;
                display: flex;
                align-items: center;
                justify-content: center;
                height: 100vh;
                margin: 0;
            }

            .container {
                background-color: #ffffff;
                padding: 40px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                width: 60%; /* Thay đổi chiều rộng theo ý muốn của bạn */
                max-width: 800px; /* Thêm giới hạn chiều rộng tối đa nếu cần */
                height: 80%; /* Thay đổi chiều cao theo ý muốn của bạn */
                max-height: 600px; /* Thêm giới hạn chiều cao tối đa nếu cần */
            }

            h2 {
                text-align: center;
                color: #007bff;
            }
            form {
                max-width: 600px; /* Thêm giới hạn chiều rộng tối đa của form */
                margin: auto; /* Đưa form về giữa */
            }

            .form-group {
                margin-bottom: 30px; /* Tăng khoảng cách giữa các trường */
            }

            label {
                display: block; /* Hiển thị label ở dòng mới */
                margin-bottom: 10px; /* Tăng khoảng cách giữa label và input */
                font-weight: bold; /* In đậm chữ cho label */
                color: #343a40; /* Màu chữ cho label */
            }

            input,
            select {
                width: 100%; /* Chiếm toàn bộ chiều rộng của form-group */
                padding: 15px; /* Tăng padding để làm cho input và select lớn hơn */
                margin-bottom: 15px; /* Tăng khoảng cách giữa các input và select */
                box-sizing: border-box; /* Kích thước toàn bộ chiều rộng và chiều cao bao gồm padding và border */
                background-color: #f8f9fa; /* Màu nền của input và select */
                border: 1px solid #ced4da; /* Màu viền của input và select */
            }

            button {
                width: 100%; /* Chiếm toàn bộ chiều rộng của form-group */
                padding: 15px;
                box-sizing: border-box;
                background-color: #007bff; /* Màu nền của nút */
                color: #ffffff; /* Màu chữ của nút */
            }


            button:hover {
                background-color: #0056b3; /* Màu nền của nút khi hover */
            }
            .btn-secondary {
                background-color: #6c757d; /* Màu nền của nút hủy bỏ */
                color: #ffffff; /* Màu chữ của nút hủy bỏ */
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            .btn-secondary:hover {
                background-color: #5a6268; /* Màu nền của nút hủy bỏ khi hover */
            }
        </style>

    </head>

    <body>
        <div class="container">
            <h2>Thêm Câu Hỏi</h2>
            <form action="/QuizPractice/question?action=insert" method="post" >
<!--                <div class="form-group">
                    <label for="questionId">Mã Câu Hỏi:</label>
                    <input type="text" class="form-control" id="questionId" name="question_id" required>
                </div>-->

                <div class="form-group">
                    <label for="questionText">Nội Dung Câu Hỏi:</label>
                    <input type="text" class="form-control" id="questionText" name="question_text" required>
                </div>

                <div class="form-group">
                    <label for="quizId">Kiểu câu hỏi:</label>
                    <select name="quiz_id" class="form-control" required>
                        <!-- Replace with your dynamic options -->
                        <option value="quiz1">Multiplechoice</option>
                        
                    </select>
                </div>

                <!-- Add more fields as needed -->

                <button type="submit" class="btn btn-primary">Tạo mới</button>
<!--                <a class="btn btn-secondary" href="#">Hủy bỏ</a>-->
            </form>
        </div>

        <!-- Essential javascripts for application to work -->
        <script src="path/to/your/jquery.min.js"></script>
        <script src="path/to/your/popper.min.js"></script>
        <script src="path/to/your/bootstrap.min.js"></script>
        <!-- The javascript plugin to display page loading on top -->
        <script src="path/to/your/pace.min.js"></script>
        <!-- Add your additional scripts here -->
    </body>

</html>

EssayGrading_G4/EssayGrading_G4/web/teacher/addQuiz.jsp
<%-- 
    Document   : addQuestion
    Created on : Mar 6, 2024, 9:34:23 AM
    Author     : -Pc-
--%>

<%@ page contentType="text/html" pageEncoding="UTF-8"  %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Thêm Câu Hỏi</title>
        <!-- Add your CSS styles here -->
        <link rel="stylesheet" type="text/css" href="path/to/your/styles.css">
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Add your additional stylesheets or frameworks here -->
        <style>
            body {
                background-color: #f8f9fa;
                display: flex;
                align-items: center;
                justify-content: center;
                height: 100vh;
                margin: 0;
            }

            .container {
                background-color: #ffffff;
                padding: 40px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                width: 60%; /* Thay đổi chiều rộng theo ý muốn của bạn */
                max-width: 800px; /* Thêm giới hạn chiều rộng tối đa nếu cần */
                height: 80%; /* Thay đổi chiều cao theo ý muốn của bạn */
                max-height: 600px; /* Thêm giới hạn chiều cao tối đa nếu cần */
            }

            h2 {
                text-align: center;
                color: #007bff;
            }
            form {
                max-width: 600px; /* Thêm giới hạn chiều rộng tối đa của form */
                margin: auto; /* Đưa form về giữa */
            }

            .form-group {
                margin-bottom: 30px; /* Tăng khoảng cách giữa các trường */
            }

            label {
                display: block; /* Hiển thị label ở dòng mới */
                margin-bottom: 10px; /* Tăng khoảng cách giữa label và input */
                font-weight: bold; /* In đậm chữ cho label */
                color: #343a40; /* Màu chữ cho label */
            }

            input,
            select {
                width: 100%; /* Chiếm toàn bộ chiều rộng của form-group */
                padding: 15px; /* Tăng padding để làm cho input và select lớn hơn */
                margin-bottom: 15px; /* Tăng khoảng cách giữa các input và select */
                box-sizing: border-box; /* Kích thước toàn bộ chiều rộng và chiều cao bao gồm padding và border */
                background-color: #f8f9fa; /* Màu nền của input và select */
                border: 1px solid #ced4da; /* Màu viền của input và select */
            }

            button {
                width: 100%; /* Chiếm toàn bộ chiều rộng của form-group */
                padding: 15px;
                box-sizing: border-box;
                background-color: #007bff; /* Màu nền của nút */
                color: #ffffff; /* Màu chữ của nút */
            }


            button:hover {
                background-color: #0056b3; /* Màu nền của nút khi hover */
            }
            .btn-secondary {
                background-color: #6c757d; /* Màu nền của nút hủy bỏ */
                color: #ffffff; /* Màu chữ của nút hủy bỏ */
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            .btn-secondary:hover {
                background-color: #5a6268; /* Màu nền của nút hủy bỏ khi hover */
            }
        </style>

    </head>

    <body>
        <div class="container">
            <h2>Add Quiz</h2>
            <form action="/QuizPractice/addQuiz" method="post" >
                <!--                <div class="form-group">
                                    <label for="questionId">Mã Câu Hỏi:</label>
                                    <input type="text" class="form-control" id="questionId" name="question_id" required>
                                </div>-->

                <div class="form-group">
                    <label for="questionText">Quiz Name:</label>
                    <input type="text" class="form-control" id="questionText" name="quiz_name" required>
                </div>
                <div class="form-group">
                    <label for="questionText">Quiz Content:</label>
                    <input type="text" class="form-control" id="questionText" name="quiz_content" required>
                </div>

                <div class="form-group">
                    <label for="quizId">Belong to Course:</label>
               
                    <input type="text" class="form-control" id="questionText" name="course_name" value="${sessionScope.courseName}" readonly>
                </div>

                <!-- Add more fields as needed -->

                <button type="submit" class="btn btn-primary">Tạo mới</button>
                <!--                <a class="btn btn-secondary" href="#">Hủy bỏ</a>-->
            </form>
        </div>
        
        <!-- Essential javascripts for application to work -->
        <script src="path/to/your/jquery.min.js"></script>
        <script src="path/to/your/popper.min.js"></script>
        <script src="path/to/your/bootstrap.min.js"></script>
        <!-- The javascript plugin to display page loading on top -->
        <script src="path/to/your/pace.min.js"></script>
        <!-- Add your additional scripts here -->
    </body>

</html>

EssayGrading_G4/EssayGrading_G4/web/teacher/editAnswer.jsp
<%-- 
    Document   : editAnswer
    Created on : Mar 6, 2024, 2:38:00 PM
    Author     : HP
--%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sửa Câu Trả Lời</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
</head>

<body>
    <div class="container mt-5">
        <h2 class="text-center mb-4">Sửa Câu Trả Lời</h2>

        <form action="EditAnswerServlet" method="post">
            <div class="form-group">
                <label for="answerId">Answer ID:</label>
                <input type="text" class="form-control" id="answerId" name="answerId" readonly>
            </div>
            <div class="form-group">
                <label for="answerText">Nội dung câu trả lời:</label>
                <textarea class="form-control" id="answerText" name="answerText" rows="3"></textarea>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="isCorrect" name="isCorrect">
                <label class="form-check-label" for="isCorrect">Đúng (Checked) / Sai (Unchecked)</label>
            </div>
            <button type="submit" class="btn btn-primary">Lưu</button>
        </form>
    </div>

    <!-- Bootstrap JS và Popper.js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>

</html>